import 'package:widget_ai/llm/agents/base_agent.dart';
import 'package:widget_ai/llm/base_model.dart';

class ReviewerAgent extends BaseAgent {
  final BaseLLMModel model;

  ReviewerAgent({required this.model})
    : super(
        name: 'Reviewer',
        role: 'QA Engineer',
        instructions: '''
You are the "Reviewer Agent." Your role is to evaluate the code generated by the Coder Agent.
Check for:
1. Adherence to the technical plan.
2. Code quality, security, and performance.
3. UI consistency and responsiveness.
4. Missing files or incomplete logic.

If the code is good, reply with "PASSED". 
If there are issues, list them clearly so the Debugger can fix them.
''',
      );

  @override
  Future<AgentResponse> process(AgentState state) async {
    final code = state.data['code'] ?? 'No code provided.';
    final plan = state.data['plan'] ?? 'No plan provided.';

    final prompt =
        '''
$instructions

Technical Plan:
$plan

Generated Code:
$code

Please review the code.
''';

    final response = await model.invoke(prompt);
    final isPassed = response.contains('PASSED');

    return AgentResponse(
      content: response,
      updatedData: {'reviewFeedback': response, 'reviewPassed': isPassed},
      isComplete: isPassed,
    );
  }
}
